# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

CMakeFiles/testBt.dir/src-lib/bacfre.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bacfre.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bacfre.c.o: ../src-lib/bacfre.c

CMakeFiles/testBt.dir/src-lib/bacini.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bacini.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bacini.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/bacini.c.o: ../src-lib/bacini.c

CMakeFiles/testBt.dir/src-lib/balbk1.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/balbk1.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/balbk1.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/balbk1.c.o: ../src-lib/balbk1.c

CMakeFiles/testBt.dir/src-lib/balblk.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/balblk.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/balblk.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/balblk.c.o: ../src-lib/balblk.c

CMakeFiles/testBt.dir/src-lib/bclrlf.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bclrlf.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bclrlf.c.o: ../src-lib/bclrlf.c

CMakeFiles/testBt.dir/src-lib/bclrst.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bclrst.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bclrst.c.o: ../src-lib/bclrst.c

CMakeFiles/testBt.dir/src-lib/bcpybk.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bcpybk.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bcpybk.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/bcpybk.c.o: ../src-lib/bcpybk.c

CMakeFiles/testBt.dir/src-lib/bdbug.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bdbug.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bdbug.c.o: ../inc/btree.h
CMakeFiles/testBt.dir/src-lib/bdbug.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/bdbug.c.o: ../src-lib/bdbug.c

CMakeFiles/testBt.dir/src-lib/bdelk1.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bdelk1.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bdelk1.c.o: ../inc/btree.h
CMakeFiles/testBt.dir/src-lib/bdelk1.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/bdelk1.c.o: ../src-lib/bdelk1.c

CMakeFiles/testBt.dir/src-lib/bdelky.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bdelky.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bdelky.c.o: ../inc/btree.h
CMakeFiles/testBt.dir/src-lib/bdelky.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/bdelky.c.o: ../src-lib/bdelky.c

CMakeFiles/testBt.dir/src-lib/bdemte.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bdemte.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bdemte.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/bdemte.c.o: ../src-lib/bdemte.c

CMakeFiles/testBt.dir/src-lib/bfndky.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bfndky.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bfndky.c.o: ../inc/btree.h
CMakeFiles/testBt.dir/src-lib/bfndky.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/bfndky.c.o: ../src-lib/bfndky.c

CMakeFiles/testBt.dir/src-lib/bgtfre.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bgtfre.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bgtfre.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/bgtfre.c.o: ../src-lib/bgtfre.c

CMakeFiles/testBt.dir/src-lib/bgtinf.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bgtinf.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bgtinf.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/bgtinf.c.o: ../src-lib/bgtinf.c

CMakeFiles/testBt.dir/src-lib/bgtslt.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bgtslt.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bgtslt.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/bgtslt.c.o: ../src-lib/bgtslt.c

CMakeFiles/testBt.dir/src-lib/binsky.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/binsky.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/binsky.c.o: ../inc/btree.h
CMakeFiles/testBt.dir/src-lib/binsky.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/binsky.c.o: ../src-lib/binsky.c

CMakeFiles/testBt.dir/src-lib/bjnblk.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bjnblk.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bjnblk.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/bjnblk.c.o: ../src-lib/bjnblk.c

CMakeFiles/testBt.dir/src-lib/bjoin.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bjoin.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bjoin.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/bjoin.c.o: ../src-lib/bjoin.c

CMakeFiles/testBt.dir/src-lib/bleaf.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bleaf.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bleaf.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/bleaf.c.o: ../src-lib/bleaf.c

CMakeFiles/testBt.dir/src-lib/bmkfre.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bmkfre.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bmkfre.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/bmkfre.c.o: ../src-lib/bmkfre.c

CMakeFiles/testBt.dir/src-lib/bmodky.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bmodky.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bmodky.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/bmodky.c.o: ../src-lib/bmodky.c

CMakeFiles/testBt.dir/src-lib/bnewap.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bnewap.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bnewap.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/bnewap.c.o: ../src-lib/bnewap.c

CMakeFiles/testBt.dir/src-lib/bnxtbk.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bnxtbk.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bnxtbk.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/bnxtbk.c.o: ../src-lib/bnxtbk.c

CMakeFiles/testBt.dir/src-lib/bnxtky.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bnxtky.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bnxtky.c.o: ../inc/btree.h
CMakeFiles/testBt.dir/src-lib/bnxtky.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/bnxtky.c.o: ../src-lib/bnxtky.c

CMakeFiles/testBt.dir/src-lib/bprvky.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bprvky.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bprvky.c.o: ../inc/btree.h
CMakeFiles/testBt.dir/src-lib/bprvky.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/bprvky.c.o: ../src-lib/bprvky.c

CMakeFiles/testBt.dir/src-lib/bputky.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bputky.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bputky.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/bputky.c.o: ../src-lib/bputky.c

CMakeFiles/testBt.dir/src-lib/brdblk.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/brdblk.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/brdblk.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/brdblk.c.o: ../src-lib/brdblk.c

CMakeFiles/testBt.dir/src-lib/bremky.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bremky.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bremky.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/bremky.c.o: ../src-lib/bremky.c

CMakeFiles/testBt.dir/src-lib/brepky.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/brepky.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/brepky.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/brepky.c.o: ../src-lib/brepky.c

CMakeFiles/testBt.dir/src-lib/bsemap.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bsemap.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bsemap.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/bsemap.c.o: ../src-lib/bsemap.c

CMakeFiles/testBt.dir/src-lib/bsetbk.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bsetbk.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bsetbk.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/bsetbk.c.o: ../src-lib/bsetbk.c

CMakeFiles/testBt.dir/src-lib/bsetbs.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bsetbs.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bsetbs.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/bsetbs.c.o: ../src-lib/bsetbs.c

CMakeFiles/testBt.dir/src-lib/bsptbk.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bsptbk.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bsptbk.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/bsptbk.c.o: ../src-lib/bsptbk.c

CMakeFiles/testBt.dir/src-lib/bsrhbk.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bsrhbk.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bsrhbk.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/bsrhbk.c.o: ../src-lib/bsrhbk.c

CMakeFiles/testBt.dir/src-lib/bstinf.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bstinf.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bstinf.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/bstinf.c.o: ../src-lib/bstinf.c

CMakeFiles/testBt.dir/src-lib/bsuper.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bsuper.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bsuper.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/bsuper.c.o: ../src-lib/bsuper.c

CMakeFiles/testBt.dir/src-lib/btchgr.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/btchgr.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/btchgr.c.o: ../inc/btree.h
CMakeFiles/testBt.dir/src-lib/btchgr.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/btchgr.c.o: ../src-lib/btchgr.c

CMakeFiles/testBt.dir/src-lib/btcls.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/btcls.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/btcls.c.o: ../inc/btree.h
CMakeFiles/testBt.dir/src-lib/btcls.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/btcls.c.o: ../src-lib/btcls.c

CMakeFiles/testBt.dir/src-lib/btcrt.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/btcrt.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/btcrt.c.o: ../inc/btree.h
CMakeFiles/testBt.dir/src-lib/btcrt.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/btcrt.c.o: ../src-lib/btcrt.c

CMakeFiles/testBt.dir/src-lib/btcrtr.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/btcrtr.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/btcrtr.c.o: ../inc/btree.h
CMakeFiles/testBt.dir/src-lib/btcrtr.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/btcrtr.c.o: ../src-lib/btcrtr.c

CMakeFiles/testBt.dir/src-lib/btdata.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/btdata.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/btdata.c.o: ../inc/btree.h
CMakeFiles/testBt.dir/src-lib/btdata.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/btdata.c.o: ../src-lib/btdata.c

CMakeFiles/testBt.dir/src-lib/btdelr.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/btdelr.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/btdelr.c.o: ../inc/btree.h
CMakeFiles/testBt.dir/src-lib/btdelr.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/btdelr.c.o: ../src-lib/btdelr.c

CMakeFiles/testBt.dir/src-lib/btdupkey.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/btdupkey.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/btdupkey.c.o: ../inc/btree.h
CMakeFiles/testBt.dir/src-lib/btdupkey.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/btdupkey.c.o: ../src-lib/btdupkey.c

CMakeFiles/testBt.dir/src-lib/btdups.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/btdups.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/btdups.c.o: ../inc/btree.h
CMakeFiles/testBt.dir/src-lib/btdups.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/btdups.c.o: ../src-lib/btdups.c

CMakeFiles/testBt.dir/src-lib/bterr.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bterr.c.o: ../src-lib/bterr.c

CMakeFiles/testBt.dir/src-lib/btinit.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/btinit.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/btinit.c.o: ../inc/btree.h
CMakeFiles/testBt.dir/src-lib/btinit.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/btinit.c.o: ../src-lib/btinit.c

CMakeFiles/testBt.dir/src-lib/btlock.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/btlock.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/btlock.c.o: ../inc/btree.h
CMakeFiles/testBt.dir/src-lib/btlock.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/btlock.c.o: ../src-lib/btlock.c

CMakeFiles/testBt.dir/src-lib/btopn.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/btopn.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/btopn.c.o: ../inc/btree.h
CMakeFiles/testBt.dir/src-lib/btopn.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/btopn.c.o: ../src-lib/btopn.c

CMakeFiles/testBt.dir/src-lib/btpos.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/btpos.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/btpos.c.o: ../inc/btree.h
CMakeFiles/testBt.dir/src-lib/btpos.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/btpos.c.o: ../src-lib/btpos.c

CMakeFiles/testBt.dir/src-lib/btque.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/btque.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/btque.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/btque.c.o: ../src-lib/btque.c

CMakeFiles/testBt.dir/src-lib/btstk.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/btstk.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/btstk.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/btstk.c.o: ../src-lib/btstk.c

CMakeFiles/testBt.dir/src-lib/btthresh.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/btthresh.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/btthresh.c.o: ../inc/btree.h
CMakeFiles/testBt.dir/src-lib/btthresh.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/btthresh.c.o: ../src-lib/btthresh.c

CMakeFiles/testBt.dir/src-lib/bupdky.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bupdky.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bupdky.c.o: ../inc/btree.h
CMakeFiles/testBt.dir/src-lib/bupdky.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/bupdky.c.o: ../src-lib/bupdky.c

CMakeFiles/testBt.dir/src-lib/butil.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/butil.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/butil.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/butil.c.o: ../src-lib/butil.c

CMakeFiles/testBt.dir/src-lib/bvalap.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bvalap.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bvalap.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/bvalap.c.o: ../src-lib/bvalap.c

CMakeFiles/testBt.dir/src-lib/bwrblk.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bwrblk.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bwrblk.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/bwrblk.c.o: ../src-lib/bwrblk.c

CMakeFiles/testBt.dir/src-lib/bxdump.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-lib/bxdump.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-lib/bxdump.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-lib/bxdump.c.o: ../src-lib/bxdump.c

CMakeFiles/testBt.dir/src-main/bt.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src-main/bt.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src-main/bt.c.o: ../inc/btcmd.h
CMakeFiles/testBt.dir/src-main/bt.c.o: ../inc/btree.h
CMakeFiles/testBt.dir/src-main/bt.c.o: ../inc/btree_int.h
CMakeFiles/testBt.dir/src-main/bt.c.o: ../src-main/bt.c

