# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# compile C with /usr/bin/cc
C_FLAGS =  

C_DEFINES = 

C_INCLUDES = -I"/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Bai1/include" -I"/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Bai1/libfdr" 

