# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Test1"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Test1"

# Include any dependencies generated for this target.
include CMakeFiles/test.dir/depend.make

# Include the progress variables for this target.
include CMakeFiles/test.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/test.dir/flags.make

CMakeFiles/test.dir/src/mainapp.c.o: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/src/mainapp.c.o: src/mainapp.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Test1/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_1) "Building C object CMakeFiles/test.dir/src/mainapp.c.o"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/test.dir/src/mainapp.c.o   -c "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Test1/src/mainapp.c"

CMakeFiles/test.dir/src/mainapp.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/test.dir/src/mainapp.c.i"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Test1/src/mainapp.c" > CMakeFiles/test.dir/src/mainapp.c.i

CMakeFiles/test.dir/src/mainapp.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/test.dir/src/mainapp.c.s"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Test1/src/mainapp.c" -o CMakeFiles/test.dir/src/mainapp.c.s

CMakeFiles/test.dir/src/mainapp.c.o.requires:

.PHONY : CMakeFiles/test.dir/src/mainapp.c.o.requires

CMakeFiles/test.dir/src/mainapp.c.o.provides: CMakeFiles/test.dir/src/mainapp.c.o.requires
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/mainapp.c.o.provides.build
.PHONY : CMakeFiles/test.dir/src/mainapp.c.o.provides

CMakeFiles/test.dir/src/mainapp.c.o.provides.build: CMakeFiles/test.dir/src/mainapp.c.o


CMakeFiles/test.dir/src/vn.c.o: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/src/vn.c.o: src/vn.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Test1/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_2) "Building C object CMakeFiles/test.dir/src/vn.c.o"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/test.dir/src/vn.c.o   -c "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Test1/src/vn.c"

CMakeFiles/test.dir/src/vn.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/test.dir/src/vn.c.i"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Test1/src/vn.c" > CMakeFiles/test.dir/src/vn.c.i

CMakeFiles/test.dir/src/vn.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/test.dir/src/vn.c.s"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Test1/src/vn.c" -o CMakeFiles/test.dir/src/vn.c.s

CMakeFiles/test.dir/src/vn.c.o.requires:

.PHONY : CMakeFiles/test.dir/src/vn.c.o.requires

CMakeFiles/test.dir/src/vn.c.o.provides: CMakeFiles/test.dir/src/vn.c.o.requires
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/vn.c.o.provides.build
.PHONY : CMakeFiles/test.dir/src/vn.c.o.provides

CMakeFiles/test.dir/src/vn.c.o.provides.build: CMakeFiles/test.dir/src/vn.c.o


CMakeFiles/test.dir/src/ja.c.o: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/src/ja.c.o: src/ja.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Test1/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_3) "Building C object CMakeFiles/test.dir/src/ja.c.o"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/test.dir/src/ja.c.o   -c "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Test1/src/ja.c"

CMakeFiles/test.dir/src/ja.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/test.dir/src/ja.c.i"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Test1/src/ja.c" > CMakeFiles/test.dir/src/ja.c.i

CMakeFiles/test.dir/src/ja.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/test.dir/src/ja.c.s"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Test1/src/ja.c" -o CMakeFiles/test.dir/src/ja.c.s

CMakeFiles/test.dir/src/ja.c.o.requires:

.PHONY : CMakeFiles/test.dir/src/ja.c.o.requires

CMakeFiles/test.dir/src/ja.c.o.provides: CMakeFiles/test.dir/src/ja.c.o.requires
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/ja.c.o.provides.build
.PHONY : CMakeFiles/test.dir/src/ja.c.o.provides

CMakeFiles/test.dir/src/ja.c.o.provides.build: CMakeFiles/test.dir/src/ja.c.o


CMakeFiles/test.dir/src/chose.c.o: CMakeFiles/test.dir/flags.make
CMakeFiles/test.dir/src/chose.c.o: src/chose.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Test1/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_4) "Building C object CMakeFiles/test.dir/src/chose.c.o"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/test.dir/src/chose.c.o   -c "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Test1/src/chose.c"

CMakeFiles/test.dir/src/chose.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/test.dir/src/chose.c.i"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Test1/src/chose.c" > CMakeFiles/test.dir/src/chose.c.i

CMakeFiles/test.dir/src/chose.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/test.dir/src/chose.c.s"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Test1/src/chose.c" -o CMakeFiles/test.dir/src/chose.c.s

CMakeFiles/test.dir/src/chose.c.o.requires:

.PHONY : CMakeFiles/test.dir/src/chose.c.o.requires

CMakeFiles/test.dir/src/chose.c.o.provides: CMakeFiles/test.dir/src/chose.c.o.requires
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/src/chose.c.o.provides.build
.PHONY : CMakeFiles/test.dir/src/chose.c.o.provides

CMakeFiles/test.dir/src/chose.c.o.provides.build: CMakeFiles/test.dir/src/chose.c.o


# Object files for target test
test_OBJECTS = \
"CMakeFiles/test.dir/src/mainapp.c.o" \
"CMakeFiles/test.dir/src/vn.c.o" \
"CMakeFiles/test.dir/src/ja.c.o" \
"CMakeFiles/test.dir/src/chose.c.o"

# External object files for target test
test_EXTERNAL_OBJECTS =

test: CMakeFiles/test.dir/src/mainapp.c.o
test: CMakeFiles/test.dir/src/vn.c.o
test: CMakeFiles/test.dir/src/ja.c.o
test: CMakeFiles/test.dir/src/chose.c.o
test: CMakeFiles/test.dir/build.make
test: CMakeFiles/test.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir="/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Test1/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_5) "Linking C executable test"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/test.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/test.dir/build: test

.PHONY : CMakeFiles/test.dir/build

CMakeFiles/test.dir/requires: CMakeFiles/test.dir/src/mainapp.c.o.requires
CMakeFiles/test.dir/requires: CMakeFiles/test.dir/src/vn.c.o.requires
CMakeFiles/test.dir/requires: CMakeFiles/test.dir/src/ja.c.o.requires
CMakeFiles/test.dir/requires: CMakeFiles/test.dir/src/chose.c.o.requires

.PHONY : CMakeFiles/test.dir/requires

CMakeFiles/test.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/test.dir/cmake_clean.cmake
.PHONY : CMakeFiles/test.dir/clean

CMakeFiles/test.dir/depend:
	cd "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Test1" && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Test1" "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Test1" "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Test1" "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Test1" "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Test1/CMakeFiles/test.dir/DependInfo.cmake" --color=$(COLOR)
.PHONY : CMakeFiles/test.dir/depend

