# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

CMakeFiles/test1.dir/src/chose.c.o: ../include/chose.h
CMakeFiles/test1.dir/src/chose.c.o: ../src/chose.c

CMakeFiles/test1.dir/src/ja.c.o: ../include/ja.h
CMakeFiles/test1.dir/src/ja.c.o: ../src/ja.c

CMakeFiles/test1.dir/src/mainapp.c.o: ../include/chose.h
CMakeFiles/test1.dir/src/mainapp.c.o: ../include/ja.h
CMakeFiles/test1.dir/src/mainapp.c.o: ../include/vn.h
CMakeFiles/test1.dir/src/mainapp.c.o: ../src/mainapp.c

CMakeFiles/test1.dir/src/vn.c.o: ../src/vn.c

