# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Bai1/libfdr"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Bai1/libfdr"

# Include any dependencies generated for this target.
include CMakeFiles/fdr.dir/depend.make

# Include the progress variables for this target.
include CMakeFiles/fdr.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/fdr.dir/flags.make

CMakeFiles/fdr.dir/dllist.c.o: CMakeFiles/fdr.dir/flags.make
CMakeFiles/fdr.dir/dllist.c.o: dllist.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Bai1/libfdr/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_1) "Building C object CMakeFiles/fdr.dir/dllist.c.o"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/fdr.dir/dllist.c.o   -c "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Bai1/libfdr/dllist.c"

CMakeFiles/fdr.dir/dllist.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/fdr.dir/dllist.c.i"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Bai1/libfdr/dllist.c" > CMakeFiles/fdr.dir/dllist.c.i

CMakeFiles/fdr.dir/dllist.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/fdr.dir/dllist.c.s"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Bai1/libfdr/dllist.c" -o CMakeFiles/fdr.dir/dllist.c.s

CMakeFiles/fdr.dir/dllist.c.o.requires:

.PHONY : CMakeFiles/fdr.dir/dllist.c.o.requires

CMakeFiles/fdr.dir/dllist.c.o.provides: CMakeFiles/fdr.dir/dllist.c.o.requires
	$(MAKE) -f CMakeFiles/fdr.dir/build.make CMakeFiles/fdr.dir/dllist.c.o.provides.build
.PHONY : CMakeFiles/fdr.dir/dllist.c.o.provides

CMakeFiles/fdr.dir/dllist.c.o.provides.build: CMakeFiles/fdr.dir/dllist.c.o


CMakeFiles/fdr.dir/fields.c.o: CMakeFiles/fdr.dir/flags.make
CMakeFiles/fdr.dir/fields.c.o: fields.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Bai1/libfdr/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_2) "Building C object CMakeFiles/fdr.dir/fields.c.o"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/fdr.dir/fields.c.o   -c "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Bai1/libfdr/fields.c"

CMakeFiles/fdr.dir/fields.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/fdr.dir/fields.c.i"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Bai1/libfdr/fields.c" > CMakeFiles/fdr.dir/fields.c.i

CMakeFiles/fdr.dir/fields.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/fdr.dir/fields.c.s"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Bai1/libfdr/fields.c" -o CMakeFiles/fdr.dir/fields.c.s

CMakeFiles/fdr.dir/fields.c.o.requires:

.PHONY : CMakeFiles/fdr.dir/fields.c.o.requires

CMakeFiles/fdr.dir/fields.c.o.provides: CMakeFiles/fdr.dir/fields.c.o.requires
	$(MAKE) -f CMakeFiles/fdr.dir/build.make CMakeFiles/fdr.dir/fields.c.o.provides.build
.PHONY : CMakeFiles/fdr.dir/fields.c.o.provides

CMakeFiles/fdr.dir/fields.c.o.provides.build: CMakeFiles/fdr.dir/fields.c.o


CMakeFiles/fdr.dir/jrb.c.o: CMakeFiles/fdr.dir/flags.make
CMakeFiles/fdr.dir/jrb.c.o: jrb.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Bai1/libfdr/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_3) "Building C object CMakeFiles/fdr.dir/jrb.c.o"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/fdr.dir/jrb.c.o   -c "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Bai1/libfdr/jrb.c"

CMakeFiles/fdr.dir/jrb.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/fdr.dir/jrb.c.i"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Bai1/libfdr/jrb.c" > CMakeFiles/fdr.dir/jrb.c.i

CMakeFiles/fdr.dir/jrb.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/fdr.dir/jrb.c.s"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Bai1/libfdr/jrb.c" -o CMakeFiles/fdr.dir/jrb.c.s

CMakeFiles/fdr.dir/jrb.c.o.requires:

.PHONY : CMakeFiles/fdr.dir/jrb.c.o.requires

CMakeFiles/fdr.dir/jrb.c.o.provides: CMakeFiles/fdr.dir/jrb.c.o.requires
	$(MAKE) -f CMakeFiles/fdr.dir/build.make CMakeFiles/fdr.dir/jrb.c.o.provides.build
.PHONY : CMakeFiles/fdr.dir/jrb.c.o.provides

CMakeFiles/fdr.dir/jrb.c.o.provides.build: CMakeFiles/fdr.dir/jrb.c.o


CMakeFiles/fdr.dir/jval.c.o: CMakeFiles/fdr.dir/flags.make
CMakeFiles/fdr.dir/jval.c.o: jval.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir="/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Bai1/libfdr/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_4) "Building C object CMakeFiles/fdr.dir/jval.c.o"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles/fdr.dir/jval.c.o   -c "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Bai1/libfdr/jval.c"

CMakeFiles/fdr.dir/jval.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/fdr.dir/jval.c.i"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Bai1/libfdr/jval.c" > CMakeFiles/fdr.dir/jval.c.i

CMakeFiles/fdr.dir/jval.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/fdr.dir/jval.c.s"
	/usr/bin/cc $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Bai1/libfdr/jval.c" -o CMakeFiles/fdr.dir/jval.c.s

CMakeFiles/fdr.dir/jval.c.o.requires:

.PHONY : CMakeFiles/fdr.dir/jval.c.o.requires

CMakeFiles/fdr.dir/jval.c.o.provides: CMakeFiles/fdr.dir/jval.c.o.requires
	$(MAKE) -f CMakeFiles/fdr.dir/build.make CMakeFiles/fdr.dir/jval.c.o.provides.build
.PHONY : CMakeFiles/fdr.dir/jval.c.o.provides

CMakeFiles/fdr.dir/jval.c.o.provides.build: CMakeFiles/fdr.dir/jval.c.o


# Object files for target fdr
fdr_OBJECTS = \
"CMakeFiles/fdr.dir/dllist.c.o" \
"CMakeFiles/fdr.dir/fields.c.o" \
"CMakeFiles/fdr.dir/jrb.c.o" \
"CMakeFiles/fdr.dir/jval.c.o"

# External object files for target fdr
fdr_EXTERNAL_OBJECTS =

libfdr.a: CMakeFiles/fdr.dir/dllist.c.o
libfdr.a: CMakeFiles/fdr.dir/fields.c.o
libfdr.a: CMakeFiles/fdr.dir/jrb.c.o
libfdr.a: CMakeFiles/fdr.dir/jval.c.o
libfdr.a: CMakeFiles/fdr.dir/build.make
libfdr.a: CMakeFiles/fdr.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir="/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Bai1/libfdr/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_5) "Linking C static library libfdr.a"
	$(CMAKE_COMMAND) -P CMakeFiles/fdr.dir/cmake_clean_target.cmake
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/fdr.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/fdr.dir/build: libfdr.a

.PHONY : CMakeFiles/fdr.dir/build

CMakeFiles/fdr.dir/requires: CMakeFiles/fdr.dir/dllist.c.o.requires
CMakeFiles/fdr.dir/requires: CMakeFiles/fdr.dir/fields.c.o.requires
CMakeFiles/fdr.dir/requires: CMakeFiles/fdr.dir/jrb.c.o.requires
CMakeFiles/fdr.dir/requires: CMakeFiles/fdr.dir/jval.c.o.requires

.PHONY : CMakeFiles/fdr.dir/requires

CMakeFiles/fdr.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/fdr.dir/cmake_clean.cmake
.PHONY : CMakeFiles/fdr.dir/clean

CMakeFiles/fdr.dir/depend:
	cd "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Bai1/libfdr" && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Bai1/libfdr" "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Bai1/libfdr" "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Bai1/libfdr" "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Bai1/libfdr" "/home/nguyenngocaocuong/Nguyen Ngo Cao Cuong/Bai1/libfdr/CMakeFiles/fdr.dir/DependInfo.cmake" --color=$(COLOR)
.PHONY : CMakeFiles/fdr.dir/depend

