// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.network.cookie.cookieBehavior", 4);
user_pref("app.normandy.user_id", "5708c577-5038-4762-92e8-ca9b605db748");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1586396293);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 450560);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1586396263);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{7089f71e-6a9a-4684-bdb5-9f838ae56ab8}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1586396288109");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1586398077109");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1586396280157");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1586399880157");
user_pref("browser.search.region", "VN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1586396281");
user_pref("browser.slowStartup.averageTime", 6567);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190718161435");
user_pref("browser.startup.homepage_override.mstone", "68.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1586396267);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1586396273202");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "68.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "e53440b6f44d4b0b9ca490969c6f52ec");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "68.0.1");
user_pref("extensions.lastPlatformVersion", "68.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"c0293fe6-7a49-4098-b43d-46b5778f10a1\",\"fxmonitor@mozilla.org\":\"ead1de3d-f9b9-4261-a12c-4d205060f52f\",\"screenshots@mozilla.org\":\"0a2fa3a9-a5ee-46fc-b19e-d1736208355d\",\"webcompat-reporter@mozilla.org\":\"480946eb-5e48-4b1d-9883-177e858e1394\",\"webcompat@mozilla.org\":\"7cd309b4-efc5-41ca-a07c-c497ead0a4e4\",\"default-theme@mozilla.org\":\"9685a195-20c7-4951-8ab9-c0357ec85f49\",\"google@search.mozilla.org\":\"29357275-94f9-4d28-9896-2ca0b49c2d75\",\"amazondotcom@search.mozilla.org\":\"3f4b9a7d-e51b-4940-980e-c301a1b7189a\",\"bing@search.mozilla.org\":\"8c9dae3a-e3cc-436a-b2d5-866e7ab9ee15\",\"ddg@search.mozilla.org\":\"9b8dcb98-884b-4b3f-9d78-2ab89f9fdaa9\",\"ebay@search.mozilla.org\":\"f38ffa49-6464-4006-80b4-8dc2c8ebd281\",\"twitter@search.mozilla.org\":\"7eb189fb-2bac-4993-9f3b-258ff6d6e332\",\"wikipedia@search.mozilla.org\":\"782f3855-313f-482b-8875-787d9053b3e4\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "c9fd4818-7555-47ec-87b6-147262368caf");
user_pref("security.sandbox.plugin.tempDirSuffix", "8ffa6fd9-cc01-4696-a4c0-37683a712e02");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1586396260);
user_pref("toolkit.telemetry.cachedClientID", "b08c8452-c017-4020-8e18-1482b9b6c67a");
user_pref("toolkit.telemetry.previousBuildID", "20190718161435");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
