# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

CMakeFiles/bai1.dir/libfdr/dllist.c.o: ../libfdr/dllist.c
CMakeFiles/bai1.dir/libfdr/dllist.c.o: ../libfdr/dllist.h
CMakeFiles/bai1.dir/libfdr/dllist.c.o: ../libfdr/jval.h

CMakeFiles/bai1.dir/libfdr/fields.c.o: ../libfdr/fields.c
CMakeFiles/bai1.dir/libfdr/fields.c.o: ../libfdr/fields.h

CMakeFiles/bai1.dir/libfdr/jrb.c.o: ../libfdr/jrb.c
CMakeFiles/bai1.dir/libfdr/jrb.c.o: ../libfdr/jrb.h
CMakeFiles/bai1.dir/libfdr/jrb.c.o: ../libfdr/jval.h

CMakeFiles/bai1.dir/libfdr/jval.c.o: ../libfdr/jval.c
CMakeFiles/bai1.dir/libfdr/jval.c.o: ../libfdr/jval.h

CMakeFiles/bai1.dir/src/compare.c.o: ../include/compare.h
CMakeFiles/bai1.dir/src/compare.c.o: ../include/data.h
CMakeFiles/bai1.dir/src/compare.c.o: ../libfdr/jval.h
CMakeFiles/bai1.dir/src/compare.c.o: ../src/compare.c

CMakeFiles/bai1.dir/src/handling.c.o: ../include/compare.h
CMakeFiles/bai1.dir/src/handling.c.o: ../include/data.h
CMakeFiles/bai1.dir/src/handling.c.o: ../include/handling.h
CMakeFiles/bai1.dir/src/handling.c.o: ../libfdr/jrb.h
CMakeFiles/bai1.dir/src/handling.c.o: ../libfdr/jval.h
CMakeFiles/bai1.dir/src/handling.c.o: ../src/handling.c

CMakeFiles/bai1.dir/src/input.c.o: ../include/compare.h
CMakeFiles/bai1.dir/src/input.c.o: ../include/data.h
CMakeFiles/bai1.dir/src/input.c.o: ../include/input.h
CMakeFiles/bai1.dir/src/input.c.o: ../libfdr/fields.h
CMakeFiles/bai1.dir/src/input.c.o: ../libfdr/jrb.h
CMakeFiles/bai1.dir/src/input.c.o: ../libfdr/jval.h
CMakeFiles/bai1.dir/src/input.c.o: ../src/input.c

CMakeFiles/bai1.dir/src/mainapp.c.o: ../include/menu.h
CMakeFiles/bai1.dir/src/mainapp.c.o: ../src/mainapp.c

CMakeFiles/bai1.dir/src/menu.c.o: ../include/compare.h
CMakeFiles/bai1.dir/src/menu.c.o: ../include/data.h
CMakeFiles/bai1.dir/src/menu.c.o: ../include/handling.h
CMakeFiles/bai1.dir/src/menu.c.o: ../include/input.h
CMakeFiles/bai1.dir/src/menu.c.o: ../include/menu.h
CMakeFiles/bai1.dir/src/menu.c.o: ../include/output.h
CMakeFiles/bai1.dir/src/menu.c.o: ../libfdr/jrb.h
CMakeFiles/bai1.dir/src/menu.c.o: ../libfdr/jval.h
CMakeFiles/bai1.dir/src/menu.c.o: ../src/menu.c

CMakeFiles/bai1.dir/src/output.c.o: ../include/data.h
CMakeFiles/bai1.dir/src/output.c.o: ../include/output.h
CMakeFiles/bai1.dir/src/output.c.o: ../libfdr/jrb.h
CMakeFiles/bai1.dir/src/output.c.o: ../libfdr/jval.h
CMakeFiles/bai1.dir/src/output.c.o: ../src/output.c

