# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

CMakeFiles/testBt.dir/src/main.c.o: ../inc/bc.h
CMakeFiles/testBt.dir/src/main.c.o: ../inc/bt.h
CMakeFiles/testBt.dir/src/main.c.o: ../inc/btree.h
CMakeFiles/testBt.dir/src/main.c.o: ../src/main.c

