# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

CMakeFiles/test1.dir/mainapp.c.o: ../libfdr/dllist.h
CMakeFiles/test1.dir/mainapp.c.o: ../libfdr/fields.h
CMakeFiles/test1.dir/mainapp.c.o: ../libfdr/jrb.h
CMakeFiles/test1.dir/mainapp.c.o: ../libfdr/jval.h
CMakeFiles/test1.dir/mainapp.c.o: ../mainapp.c

